# Andrés Álvarez Carou

# Guía Python



## Introducción y comandos básicos:

* `and`, `or` y `not`  son los operadores booleanos para and, or y not


* // Es la floor division (nos devuelve el entero más próximo


* % devuelve el residuo de una división


* range(i,j) secuencia de numeros de i a j-1


* float(x) convierte un numero entero x en float


* str(x) convierte un valor numerico x en string

Los if tienen la siguiente estructura

```python
if test1:
    statement_1
elif test2:
    statement_2
elif test3:
    statement_3
else:
    statement_4
```

Y los for

```python
for item in sequence:
    statement_1
else:
    statement_2
```

Es importante no olvidar poner 2 puntos al final de los test y hacer buena indexación

In [1]:
for i in range(1,5):
    if i==3:
        break
else:
    print("Hola mundo")

        
            
    

In [2]:
i=len(range(1,5))
print(i)
for i in range(1,5):
    print(i)

4
1
2
3
4


### Listas

Son secuencias de objetos

* Las listas están ordenadas mediante un índice numérico y el primero 
de estes es el 0

* Para acceder a los elementos tenemos que poner el índice entre corchetes. 

* Las listas son objetos mutables, esto quiere decir que si creamos una lista
a partir de otra y modificamos esta última, entonces la primera se modificará también (no se crea una nueva copia). Veamos un ejemplo: 

In [3]:
lista=[1,2,3,4,5]
lista1=lista
lista1[1]=6
print(lista1)
print(lista)


[1, 6, 3, 4, 5]
[1, 6, 3, 4, 5]



Para solventar esto podemos crear copias de la lista. 
Tenemos 2 maneras diferentes de realizar esta acción: 

* Una manera es añadir [:] al final de nuestra lista original en la nueva asignación 



* Otro modo será mediante .copy()

In [4]:
lista=[1,2,3,4,5]
lista1=lista[:]
lista1[1]=6
print(lista1)
print(lista)

[1, 6, 3, 4, 5]
[1, 2, 3, 4, 5]


In [5]:
lista=[1,2,3,4,5]
lista1=lista.copy()
lista1[1]=6
print(lista1)
print(lista)

[1, 6, 3, 4, 5]
[1, 2, 3, 4, 5]


Podemos modificar cómodamente las listas mediante los siguientes comandos: 

  * Mediante el método `append`.  Añade un elemento al final de la lista
  * Mediante el método `insert`.  Eliges la posición del elemento
  * Mediante el método `extend`.  Añade una nueva lista a la anterior

In [6]:
lista = ["Hola", "todos,", "que", "tal"]
lista.append("estáis?")  #Añades un elemento 
print("Después de append:", lista)

lista.insert(1, "a")  #eliges la posición del nuevo elemento
print("Después de insert:", lista)

lista.extend(["Espero", "que", "bien"])  #Añades una nueva lista a la lista previa
print("Después de extend:", lista)

Después de append: ['Hola', 'todos,', 'que', 'tal', 'estáis?']
Después de insert: ['Hola', 'a', 'todos,', 'que', 'tal', 'estáis?']
Después de extend: ['Hola', 'a', 'todos,', 'que', 'tal', 'estáis?', 'Espero', 'que', 'bien']


También podemos eliminar elementos de nuestras listas mediante: 

  * Mediante el método `remove`. Elimina lo que le indicamos
  * Mediante el método `pop`.   Elimina el último elemento
  * Mediante la function `del`.  Elimina mediante el índice

In [7]:
lista.remove("Hola")
print('Elimino "Hola":', lista)

lista.pop()
print('Elimino el último elemento:', lista)

del lista[3]
print("Elimino el elemento del índice 3:", lista)


Elimino "Hola": ['a', 'todos,', 'que', 'tal', 'estáis?', 'Espero', 'que', 'bien']
Elimino el último elemento: ['a', 'todos,', 'que', 'tal', 'estáis?', 'Espero', 'que']
Elimino el elemento del índice 3: ['a', 'todos,', 'que', 'estáis?', 'Espero', 'que']


Las tuplas son secuencias de objetos están ordenadas, son inmutables y no se pueden modificar. 

In [8]:
t=(1,2,3)

t=(1,) #Para crear tuplas de 1 elemento

### Diccionarios

Un diccionarios es un conjunto de pares `clave:valor` y se define mediante corchetes

* Para crear un diccionario podemos hacerlo de 2 maneras diferentes. 
    * `{}` y escribir los pares separados por :
    * Mediante el comando `dict()` y separar los elementos mediante pares ()
    
    


In [9]:
diccionario1={1:"Szymon",2:"Julia",3:"Jesus"}
diccionario2=dict([(1,"Szymon"),(2,"Julia"),(3,"Jesus")])
diccionario3=dict(uno="Szymon", dos="Julia", tres="Jesus") 
#en diccionario3 no podemos definir claves con enteros
print(diccionario1)
print(diccionario2)
print(diccionario3)

diccionario1[1]
#diccionario1["Szymon"]  #No se puede accceder mediante el valor,
                         #   solamente la clave
    
diccionario3["dos"]    

{1: 'Szymon', 2: 'Julia', 3: 'Jesus'}
{1: 'Szymon', 2: 'Julia', 3: 'Jesus'}
{'uno': 'Szymon', 'dos': 'Julia', 'tres': 'Jesus'}


'Julia'

In [10]:
diccionario={"Nombre":"Andrés", "Apellidos":"Álvarez", "edad":23}
print(diccionario)
#diccionario[1] #No accedemos mediante indexacion
diccionario["Nombre"]="Andresito"
diccionario["edad"]+=1
print(diccionario)
"Nombre" in diccionario
"Andresito" in diccionario




{'Nombre': 'Andrés', 'Apellidos': 'Álvarez', 'edad': 23}
{'Nombre': 'Andresito', 'Apellidos': 'Álvarez', 'edad': 24}


False

In [11]:
diccionario={"Nombre":"Andrés", "Apellidos":"Álvarez", "edad":23}
print(diccionario)

print(diccionario.keys())
print(diccionario.values())

diccionario.pop("Nombre")
print(diccionario)

#Para hacer copia del diccionario hacemos igual que las listas 
#con el comando .copy()

{'Nombre': 'Andrés', 'Apellidos': 'Álvarez', 'edad': 23}
dict_keys(['Nombre', 'Apellidos', 'edad'])
dict_values(['Andrés', 'Álvarez', 23])
{'Apellidos': 'Álvarez', 'edad': 23}


### Funciones

In [12]:
import math
def funcion1(x,y):
    
    
    
    if x%2==0:
        print(x, " es un número par")
        
    raiz=math.sqrt(y)

    return(raiz)


funcion1(2,9) #cuidado co la indexacion
   
    

2  es un número par


3.0

### Módulos y paquetes

In [13]:
import math as matematicas

from math import sqrt as raiz

raiz(9)

3.0

Para más detalles, mirar el ejercicio 4.2 y 4.3

A la hora de crear un paquete es importante crear el 
fichero `__init__.py` para que python reconozca que es un fichero



## Programación orientada a objetos (OOP)

In [14]:
a="hola"
b=5
print(type(a))
print(type(b))

<class 'str'>
<class 'int'>


* Un objeto es una instancia de una clase 
* Podemos crear nuevas clases mediante el comando `class`
* Una clase puede heredar de una clase padre sus atributos y metodos
* Todo en Python son objetos, por lo que es conveniente heredar siempre
de la clase objeto
* Utilizamos `__ini__` para inicializar la nueva clase


* Hay comandos especificos para trabajar las operaciones básicas
     * `__add__(self, other)`: `self + other` 
 * `__sub__(self, other)`: `self - other`
 * `__eq__(self, other)`: `self == other`
 * `__lt__(self, other)`: `self < other`
 * `__len__(self)`: `len(self)`
 * `__str__(self)`: `print self`

In [15]:
#Vamos a crear una clase

class Piso(object):
    carrera=None
    
    def __init__(self, name, edad):
        self.name=name
        self.edad=edad
    
    def __str__(self):
        return "El miembro del piso "+self.name+" estudia la carrera de "+self.carrera
    
class Matematicas(Piso):
    carrera="Matematicas"
    
class Fisica(Piso):    
    carrera="Fisica"

In [16]:
a=Matematicas("andres",23)
print(a)
print(type(a))    

#Hemos creado la clase matematicas que hereda directamente de la clase piso

El miembro del piso andres estudia la carrera de Matematicas
<class '__main__.Matematicas'>


In [23]:
#esto es un trasteo mío con las clases

class Piso(object):
    
    
    def __init__(self, name, edad):
        self.name=name
        self.edad=edad
    
    def __str__(self):
        return "El miembro del piso "+self.name+self.carrera
    
class Matematicas(Piso):
    
    
    def __init__(self,carrera):
        self.carrera=carrera
    def __str__(self):
        return "el compañero es" + self.name + "la carrera es "+self.carrera
    


## Paquete Numpy

* Paquete muy importante para operaciones matemáticas, ya que podremos trabajar con arrays y vectores

In [40]:
import numpy

a=numpy.array([1,2,3,4]) #Vector
b=numpy.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(b)
b[0,0]   #No nos olviemos que el indexing empieza en el cero 
c=numpy.random.randint(10,size=(3,3,3))
print(c)


[1 2 3 4]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 6 8]
  [3 4 0]
  [0 6 4]]

 [[0 4 6]
  [0 3 1]
  [0 0 4]]

 [[6 6 4]
  [2 2 1]
  [9 9 7]]]


In [43]:
print(c[0,1,1])
print(c[1,1,2])
b[:,2]
b[2,:]

4
1


array([7, 8, 9])

El comando `.reshape()` cambia la forma del array según la nueva dimensión que le demos

Para transponerlo utilizaremos `transpose()` o `.T`

In [49]:
g=numpy.arange(1,18,2)
g2=g.reshape(3,3)
print(g2)

g2.transpose()
g2.T

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


array([[ 1,  7, 13],
       [ 3,  9, 15],
       [ 5, 11, 17]])

## Paquete Pandas

* Pandas es un paquete de Python que implementa ciertos tipos de datos, construidos sobre `numpy`
* Los tipos básicos de Pandas son
    * Series: 1 dimensión
        * Un array 1D con etiquetas en sus ejes.
    * DataFrames: 2 dimensiones
        * Datos en formato tabular, con etiquetas en sus ejes.
    * Un DataFrame son datos tabulares (tablas)

In [55]:
import numpy
import pandas

Para crear una `Serie` utilizaremos `pandas.Series()`

Estas series serán arrays de 1D pero con etiquetas, veamos un ejemplo


In [60]:
s=pandas.Series(numpy.arange(1,5,1))
print(s)
print(s.values)
print(type(s.values))
s.index

0    1
1    2
2    3
3    4
dtype: int64
[1 2 3 4]
<class 'numpy.ndarray'>


RangeIndex(start=0, stop=4, step=1)

In [70]:
#Cuando hacemos indexing, lo hacemos a las etiquetas, no a los valores

s[0]

s2=pandas.Series([1,2,3,4,5],index=["uno","dos","tres","cuatro","cinco"])
print(s2)
print(s2[1])
print(s2["dos"])





uno       1
dos       2
tres      3
cuatro    4
cinco     5
dtype: int64
2
2


In [78]:
#Indices implicitos y explicitos

s3=pandas.Series([3,4,5,6,7,8],index=[2,3,4,5,6,7])
print(s3)

#Para el índice implicito usamos .iloc (la posicion real del index)
print(s3.iloc[3])

#Para el índice explícito usamos .loc (el nombre que le hemos 
#puesto al apendice)

print(s3.loc[3])
print(s3[3])   #por defecto es el explicito

2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64
6
4
4


Podemos crear una serie a partir de un diccionario

In [67]:
edad = {
    "maria": 25,
    "pedro": 76,
    "arturo": 80,
    "rosa": 19,
}

pandas.Series(edad)

maria     25
pedro     76
arturo    80
rosa      19
dtype: int64

Un DataFrame es una representación de datos con etiquetas que 
pueden tener más de una dimensión

Para crear un DataFrame: 

`pandas.DataFrame(data=None, index=None, dtype=None, copy=None)`

Podemos crear DataFrame a partir de un diccionario o de series

In [68]:
# A través de varias Series

edad = {
    "maria": 25,
    "pedro": 76,
    "arturo": 80,
    "rosa": 19,
}

edad = pandas.Series(edad)

altura = {
    "maria": 1.75,
    "pedro": 1.90,
    "arturo": 1.68,
    "rosa": 1.65,
}

altura = pandas.Series(altura)

personas = pandas.DataFrame({"edad": edad, "altura": altura})
personas

edad  altura
maria     25    1.75
pedro     76    1.90
arturo    80    1.68
rosa      19    1.65

In [96]:
print(personas["edad"])
print(personas.edad)

print(personas.values[0])

print(personas.edad.values[1])
print(personas.values[1,0])

#también podemos utilizar .loc e .iloc

print(personas.iloc[1,0])

print(personas.loc[personas.edad > 50])
print(personas.edad.loc[personas.edad > 50])

maria     25
pedro     76
arturo    80
rosa      19
Name: edad, dtype: int64
maria     25
pedro     76
arturo    80
rosa      19
Name: edad, dtype: int64
[25.    1.75]
76
76.0
76
        edad  altura
pedro     76    1.90
arturo    80    1.68
pedro     76
arturo    80
Name: edad, dtype: int64
